server:
  port: 8082

spring:
  application:
    name: ddalkkak

  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
#
#  security:
#    oauth2:
#      client:
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id
#        registration:
#          kakao:
#            client-id: 4b7adc32013accf7909b512bd1f252ac
#            client-secret: rfm4eja7oEH6h0GyR4GqQOpE5j8zIdoM
#            client-authentication-method: client_secret_post
#            redirect-uri: http://localhost:8082/login/oauth2/code/kakao
#            authorization-grant-type: authorization_code
#            client-name: kakao
#            scope:
#              - profile_nickname
#              - account_email

kakao:
  login:
    success:
      client-redirect-uri: http://localhost:3000/login/success

### upload file limit
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB

#### SWAGGER
springdoc:
  swagger-ui.path: /swagger-ui.html
  api-docs.path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default: true
    display-query-params-without-oauth2: true
    doc-expansion: none





logging:
  level:
    org:
      springframework:
        security=DEBUG:
    root: info