server:
  port: 8082

spring:
  application:
    name: ddalkkak

  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

### upload file limit
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
      enabled: true
#### SWAGGER

#swagger-ui ??
#swagger-ui ?? ??(http://localhost:{server.port}/swagger-ui/index.html)
springdoc:
  swagger-ui.path: /swagger-ui.html
  #OpenAPI JSON ?? ?? ?? (http://localhost:{server.port}/api-docs)
  api-docs.path: /api-docs
  #?? ?? ??? json
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    #ui ??? ? ??
    operations-sorter: alpha
    tags-sorter: alpha
    #swagger url ????, json? ? config ?? ?? ????? ???? swagger-ui? ????? ?
    disable-swagger-default: true
    display-query-params-without-oauth2: true
    doc-expansion: none

logging:
  level:
    root: info
