server:
  port: 8082

spring:
  application:
    name: ddalkkak

  datasource:
    url: jdbc:h2:mem:ddaldb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true


  h2:
    console:
      enabled: true
      path: /h2-console

  ### upload file limit
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
